// CLIENT-SIDE FILE DOWNLOADS FOR A BACKEND-LESS POC.
//
// There is no file store — a "document" here is a name plus the facts the app
// already holds. Opening one renders those facts into a plain-text file at the
// moment of the click, so the download is honest about what the system knows
// rather than shipping a hollow placeholder PDF.

/** Trigger a browser download of `content` as `fileName`. Client-side only. */
export function downloadTextFile(fileName: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName.replace(/\.pdf$/i, ".txt");
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** A readable mock rendering: title block, the facts on file, then the body. */
export function mockDocContent(
  title: string,
  orderNo: string,
  meta: Record<string, string | undefined>,
  body?: string,
): string {
  const lines = [
    "═".repeat(58),
    `  ${title.toUpperCase()}`,
    `  Order ${orderNo} · generated by 1Source Ops (demo document)`,
    "═".repeat(58),
    "",
    ...Object.entries(meta)
      .filter(([, v]) => v)
      .map(([k, v]) => `${k.padEnd(22)}: ${v}`),
  ];
  if (body?.trim()) lines.push("", "─".repeat(58), "", body.trim());
  lines.push("", "─".repeat(58), "This file is a demo rendering of the record held in the app.");
  return lines.join("\n");
}
